### ISSUE TITLE
websocket の schema 書く

### ISSUE THREAD

**Issue by SSlime-s** [hackathon-22-winter-01/front-end#1]
https://github.com/hackathon-22-winter-01/front-end/blob/main/src/lib/websocket.ts
のとこで zod の schema 書く

**Comment by ras0q** [comment]
これapi-genとかから自動生成できないのか
バックエンドはそうしてるけど

**Comment by SSlime-s** [comment]
zod 使おうとしてるのが悪い説もある

**Comment by SSlime-s** [comment]
書くの単純作業だしそんな時間かかんない (はず) だからまぁええかののりではある
